### ISSUE TITLE
trash command not documented

### ISSUE THREAD

**Issue by AvaPL** [andreafrancia/trash-cli#194] opened 2021-02-07 13:54 UTC
**Is your feature request related to a problem? Please describe.**
It is good to know that `trash` is an alias to `trash-put`. It also doesn't have a man page so you have to look into the source to check what it does.

**Describe the solution you'd like**
Add `trash` man page and include it in README.md.

**Comment by andreafrancia** [comment] 2021-04-04 13:43
`trash` is a duplicate of `trash-put`. I am thinking of removing it altogether.

**Comment by pabs3** [comment] 2021-04-09 02:10
I would suggest to make trash-cli like git, with `trash` as the main command and the other commands as sub-commands, so you would call `trash put` or `trash rm` rather than `trash-put`.

**Comment by andreafrancia** [comment] 2021-05-12 20:01
Fixed in 0e77ec6

**Closed by andreafrancia** 2021-05-12 20:01 UTC
