### ISSUE TITLE
Neither trash-restore nor GUI file manager can see deleted file

### ISSUE THREAD

**Issue by jamadagni** [andreafrancia/trash-cli#110] opened 2017-12-02 10:41 UTC
Hello. Please see the following session transcript:

    $ mkdir /tmp/new
    $ cd /tmp/new
    $ ls -la
    total 0
    drwxrwxr-x 1 samjnaa samjnaa    0 Dec  2 16:04 .
    drwxrwxrwt 1 root    root    1140 Dec  2 16:04 ..
    $ touch tempfile
    $ trash -v tempfile
    trash: Volume of file: /tmp
    trash: Trash-dir: /home/samjnaa/.local/share/Trash from volume: /home
    trash: found unusable .Trash dir (should be a dir): /tmp/.Trash
    trash: Trash-dir: /tmp/.Trash-1000 from volume: /tmp
    trash: 'tempfile' trashed in /tmp/.Trash-1000
    $ trash-restore
    No files trashed from current dir ('/tmp/new')
    $ trash --version
    trash 0.17.1.14

I checked with my file manager Dolphin's trash display and the deleted file is not appearing there either.

I should note that `/tmp/` is a separate mountpoint on my system. Likewise, `/mnt/data` is a separate mountpoint, and files `trash`-ed there aren't visible later either, whether from the same dir or another. Only deleted files under `~` seem to be visible later.

Please advise!

**Comment by victorz** [comment] 2017-12-31 12:41
I can confirm trash-cli doesn't recognize trashed files on separate partitions/file systems.

**Comment by jpbegin** [comment] 2019-01-10 15:40
```
root@jpb-ubuntu16-64:~# ls
root@jpb-ubuntu16-64:~# touch test3.txt
root@jpb-ubuntu16-64:~# ls
test3.txt
root@jpb-ubuntu16-64:~# trash test3.txt
root@jpb-ubuntu16-64:~# ls
root@jpb-ubuntu16-64:~# trash-list
2019-01-10 09:17:54 /root/bsplayer-13_1_0-23201-amd64.deb
2019-01-10 10:29:33 /root/test2.txt
2019-01-10 09:17:54 /root/txt.txt
2018-11-15 15:54:29 /home/bsp/.config/Alex_BroadSign.conf
2018-11-15 15:54:32 /home/bsp/.config/BroadSign.conf
2019-01-10 10:30:32 /root/test3.txt
2019-01-10 09:17:54 /root/test.txt
2018-11-15 09:35:55 /root/test.txt
2019-01-08 16:19:33 /opt/broadsign/suite/bsp/lib/i965_drv_video.so
2019-01-10 09:17:54 /root/txt
root@jpb-ubuntu16-64:~# restore-trash
   0 2019-01-10 09:17:54 /root/bsplayer-13_1_0-23201-amd64.deb
   1 2019-01-10 10:29:33 /root/test2.txt
   2 2019-01-10 09:17:54 /root/txt.txt
   3 2019-01-10 10:30:32 /root/test3.txt
   4 2019-01-10 09:17:54 /root/test.txt
   5 2018-11-15 09:35:55 /root/test.txt
   6 2019-01-10 09:17:54 /root/txt
What file to restore [0..6]: 3
root@jpb-ubuntu16-64:~# ls
test3.txt
root@jpb-ubuntu16-64:~# trash test3.txt
```

Im also having an issue. I wanted to recover `/opt/broadsign/suite/bsp/lib/i965_drv_video.so` but I'm not sure how now. I've googled a bit to find out the trash bin path but no luck. Anybody know if it's possible to restore a file manually from the trash bin by any chance? Thanks in advance for the help.

**Comment by Gim6626** [comment] 2020-03-17 05:34
Seems that I've faced similar bug, tried to trash directory and restore it immediately:
```
[10:25]dvinokurov@DVinokurov-WorkPC[ci]$ trash docs/
[10:31]dvinokurov@DVinokurov-WorkPC[ci]$ trash-restore docs/
No files trashed from current dir ('/home/dvinokurov/work/Avigdor-second/tools/ci')
```

**Comment by Gim6626** [comment] 2020-06-15 06:45
Note - when I restore using full path it works:
```
[11:44]d.vinokurov@MacBook-Pro-DVinokurov[build]$ trash foo
[11:44]d.vinokurov@MacBook-Pro-DVinokurov[build]$ ls | grep foo
[11:44]d.vinokurov@MacBook-Pro-DVinokurov[build]$ trash-restore foo
No files trashed from current dir ('/Users/d.vinokurov/hacking/input-source-switcher/build')
[11:44]d.vinokurov@MacBook-Pro-DVinokurov[build]$ trash-list | grep foo
2020-06-15 11:44:29 /Users/d.vinokurov/hacking/input-source-switcher/build/foo
[11:44]d.vinokurov@MacBook-Pro-DVinokurov[build]$ trash-restore /Users/d.vinokurov/hacking/input-source-switcher/build/foo
   0 2020-06-15 11:44:29 /Users/d.vinokurov/hacking/input-source-switcher/build/foo
What file to restore [0..0]: 0
[11:44]d.vinokurov@MacBook-Pro-DVinokurov[build]$ ls | grep foo
foo
```

**Comment by andreafrancia** [comment] 2020-12-11 20:13
Please retry with new latest version of trash-cli (installed with `pip install trash-cli` not from apt or similar).

**Comment by Gim6626** [comment] 2020-12-25 06:14
Still does not work:
```
[11:12]dmitriy@dmitriy-ThinkPad-X1-Carbon-Gen-8[hacking]$ pip3 list | grep trash
trash-cli              0.20.11.23          
[11:13]dmitriy@dmitriy-ThinkPad-X1-Carbon-Gen-8[hacking]$ touch foo
[11:13]dmitriy@dmitriy-ThinkPad-X1-Carbon-Gen-8[hacking]$ trash foo
[11:13]dmitriy@dmitriy-ThinkPad-X1-Carbon-Gen-8[hacking]$ trash-restore foo
No files trashed from current dir ('/home/dmitriy/hacking')
```

**Comment by KSR-Yasuda** [comment] 2020-12-25 07:04
Since v0.20.11.14, perhaps #178 is related to this a bit? (I have no idea about the older versions, though...)

[`psutil.disk_partitions()`](https://psutil.readthedocs.io/en/latest/#psutil.disk_partitions), that has been introduced at that version, does not show non-physical devices:
it ignores such as memory (means tmpfs?), duplicated partitions, etc.

I think you should check **what kind of partition** the missing file had existed in.

**Comment by Gim6626** [comment] 2020-12-25 07:06
I've got one partition for whole system

**Comment by andreafrancia** [comment] 2020-12-25 20:52
@Gim6626 : please use `trash-restore $PWD/foo` for now, trash-restore currently does not understand relative path

**Comment by andreafrancia** [comment] 2020-12-25 20:54
@jpbegin in order to see the file at `/opt/*/suite/*/lib/i965_drv_video.so` you need to launch trash-restore like this:

```
$ trash-restore /
```

When called without argument trash-restore list only files trashed from the current directory

**Comment by andreafrancia** [comment] 2020-12-25 20:56
@jamadagni many things may have changed since the version 0.17.1.14 (January 14th 2017) please try with an update version of trash-cli

**Comment by Gim6626** [comment] 2020-12-26 06:37
> @Gim6626 : please use `trash-restore $PWD/foo` for now, trash-restore currently does not understand relative path

Does this behaviour have some specific reason? Seems that it is very easy to substitute $PWD in source code instead of asking users do it on their own.

**Comment by andreafrancia** [comment] 2020-12-26 15:01
> Does this behaviour have some specific reason? 
I don't remember if there was a reason. Maybe it was an oversight or a regression.

> Seems that it is very easy to substitute $PWD in source code instead of asking users do it on their own.
If you want you can fork the code and modify the feature as you want. Pull Request are welcome.

**Comment by andreafrancia** [comment] 2021-01-13 19:26
Closing as the original poster does not give feedback

**Closed by andreafrancia** 2021-01-13 19:26 UTC
